# Login Page Elements
txt_username = "name:username"
txt_password = "name:password"
btn_login = "xpath://button[contains(., 'Login')]"
verifyLogin = "xpath://div[@class ='oxd-brand-banner']"

# Recruitment Page Elements
btn_recruitment = "xpath://span[@class='oxd-text oxd-text--span oxd-main-menu-item--name' and contains(.,'Recruitment')]"
btn_addRecruitment = "xpath://button[contains(., 'Add')]"
txt_firstName = "name:firstName"
txt_middleName = "name:middleName"
txt_lastName = "name:lastName"
dropdown_vacancy = "xpath://label[@class = 'oxd-label' and contains(text(), 'Vacancy')]/parent::div/following-sibling::div//div[@class='oxd-select-text-input']"
selectDropdown_vacancyTitle = "xpath://div[@class = 'oxd-select-text-input']"
dropdownOption_vacancyTitle = "xpath://div[@role='option' and contains(.,'Software Engineer')]"
txt_email = "xpath://label[@class = 'oxd-label oxd-input-field-required' and contains(., 'Email')]/parent::div/following-sibling::div/input"
upload_fileInput = "xpath://input[@type='file']"
uploaded_fileTitle = "xpath://div[@class = 'oxd-file-input-div']"
btn_calendar = "xpath://input[@placeholder='yyyy-dd-mm']"
checkbox_recruitement = "xpath://i[@class='oxd-icon bi-check oxd-checkbox-input-icon']"
checkboxed_checked = "xpath://input[@type='checkbox']"
btn_candidatesTab = "xpath://a[text() = 'Candidates']"
dropdown_status = "xpath://label[@class = 'oxd-label' and contains(text(), 'Status')]/parent::div/following-sibling::div//div[@class='oxd-select-text-input']"
dropdownOption_status = "xpath://div[@role='option' and contains(.,'Application Initiated')]"
txt_candidateName = "xpath://input[@placeholder = 'Type for hints...']"
dropdownOption_candidateName = "xpath://div[@role='option' and contains(.,'Paul John Lee')]"
btn_delete = "xpath://i[@class = 'oxd-icon bi-trash']"
dioalogueBox_delete = "xpath://div[@class = 'orangehrm-modal-footer']/button[2]"
txtTitle_Recruitement = "xpath://span[@class = 'oxd-topbar-header-breadcrumb']/h6"
txtTitle_addCandidate = "xpath://div[@class = 'orangehrm-card-container']/h6"
txt_searchedRow1 = "xpath://div[@class='oxd-table-card']/div/div[3]/div"
toast_confirmDelete = "xpath://div[@id='oxd-toaster_1']//p[2]"
